name: "Trigger_Azure_Container"
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Trigger Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            name: mfl-watcher
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/mfl-watcher:${{ github.sha }}
            cpu: 1
            memory: 1
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            azure-file-volume-account-name: ${{ secrets.VOLUME_ACCOUNT_NAME }}
            azure-file-volume-account-key: ${{ secrets.VOLUME_ACCOUNT_KEY }}
            azure-file-volume-share-name: 'mflwatcher-storage'
            azure-file-volume-mount-path: '/app/storage/'
            location: 'eastus'
            restart-policy: "Always"
