name: Deploy via SSH
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Stop MFL watcher
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ~mflwatcher/MFL_watcher/ && sudo -u mflwatcher ./bin/stop.sh
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
        env:
          CI: true
